function init(self)
	msg.post(".", "acquire_input_focus")
	self.vel = vmath.vector3()
	self.step = 250
end

function update(self, dt)
	local pos = go.get_position()
	pos = pos + self.vel * dt
	go.set_position(pos)
	self.vel.x = 0
end

function on_input(self, action_id, action)
	if action_id == nil then
		return
	end
	if action_id == hash("left") then
		self.vel.x = -self.step
	elseif action_id == hash("right") then
		self.vel.x = self.step
	end
end